export const hsk1 = [
  ["1", "Personal Pronoun", "我", "wǒ", "I, me", "Yo, mí", "我不信。"],
  ["2", "Personal Pronoun", "我们", "wǒmen", "We, us （pl.）", "Nosotros, nuestro", "我们在商店。"],
  ["3", "Personal Pronoun", "你", "nǐ", "You", "Tú", "你有多少钱"],
  ["4", "Personal Pronoun", "你们", "nǐmen", "You (pl.)", "Vosotros, vuestro", "你们去哪里?"],
  ["5", "Personal Pronoun", "他", "tā", "He, him", "Él, le", "他是我的朋友。"],
  ["6", "Personal Pronoun", "她", "tā", "She, her", "Ella, la", "她是我的同学。"],
  ["7", "Personal Pronoun", "他们", "tāmen", "They", "Ellos", "他们想去看电影。"],
  ["8", "Personal Pronoun", "她们", "tāmen", "They", "Ellas", "她们是我的同学。"],
  ["9", "Demostrative Pronoun", "这 (这儿)", "zhè ( zhèr)", "Here, this", "Aquí, esto", "这地方很漂亮。"],
  ["10", "Demostrative Pronoun", "那 (那儿)", "nà (nàr)", "There, that", "Allí, eso", "那是我的书。"],
  ["11", "Interrogative Pronoun", "哪（哪儿）", "nǎ (nǎr)", "Which (Where)", "Cuál (Dónde)", "哪个在打电话？"],
  ["12", "Interrogative Pronoun", "谁", "shuí", "Who", "Quien", "他是谁?"],
  ["13", "Interrogative Pronoun", "什么", "shén me", "What", "Que", "你喜欢吃什么?"],
  ["14", "Interrogative Pronoun", "多少", "duōshǎo", "How many, How much", "Cuánto", "这儿有多少本书?"],
  ["15", "Interrogative Pronoun", "几", "jǐ", "How many(smaller than 10)", "Cuánto(por debajo de 10)", "你儿子几岁?"],
  ["16", "Interrogative Pronoun", "怎么", "zěnme", "How", "Cómo", "你怎么回家?"],
  ["17", "Interrogative Pronoun", "怎么样", "zěnmeyàng", "How is it", "Cómo es", "今天天气怎么样?"],
  ["18", "Conjuction", "和", "hé", "And", "Y", "我和他是同学。"],
  ["19", "Preposition", "在", "zài", "In, on, at", "En", "他们在学校学习汉语。"],
  ["20", "Numeral", "一", "yī", "One", "Uno", "我有一个妹妹。"],
  ["21", "Numeral", "二", "èr", "Two", "Dos", "一是一，二是二。"],
  ["22", "Numeral", "三", "sān", "Three", "Tres", "这儿有三本书。"],
  ["23", "Numeral", "四", "sì", "Four", "Cuatro", "我家有四口人。"],
  ["24", "Numeral", "五", "wǔ", "Five", "Cinco", "现在五点了。"],
  ["25", "Numeral", "六", "liù", "Six", "Seis", "那儿有六个苹果。"],
  ["26", "Numeral", "七", "qī", "Seven", "Siete", "我有七个学生。"],
  ["27", "Numeral", "八", "bā", "Eight", "Ocho", "我们八个人是好朋友。"],
  ["28", "Numeral", "九", "jiǔ", "Nine", "Nueve", "他九岁了。"],
  ["29", "Numeral", "十", "shí", "Ten", "Diez", "这本书十块钱。"],
  ["30", "Numeral", "零", "líng", "Zero", "Cero", "他考了零分。"],
  ["32", "Quantifier", "个", "gè", "General measure", "Medidor general", "一个人"],
  ["33", "Quantifier", "岁", "suì", "Year (of age)", "Años", "我五岁。"],
  ["34", "Quantifier", "本", "běn", "Books, dictionary, etc", "Libros,  diccionario, etc", "我有两本汉语书。"],
  ["35", "Quantifier", "些", "xiē", "Some, a few", "Algunos", "你多喝些水。"],
  ["36", "Quantifier", "块", "kuài", "Unit of money, a piece(cake)", "Unidad de Dinero, una pieza(pastel)", "这个杯子十块钱。"],
  ["37", "Auxiliary", "的", "de", "Part. used after an attribute", "Part. utilizada después de un atributo", "这是我的书。"],
  ["38", "Auxiliary", "了", "le", "1-Change or new circumstance. 2-after a verb: action is completed", "1-Cambio o nueva circunstancia. 2-Después de un verbo: se ha completado la acción", "我看了那个电影。"],
  ["39", "Auxiliary", "吗", "ma", "End of a question", "Final de una pregunta", "你是中国人吗?"],
  ["40", "Auxiliary", "呢", "ne", "End of a question", "Final de una pregunta", "爸爸在哪儿呢?"],
  ["41", "Interjection", "喂", "wèi", "Hey(phone call)", "Digame (llamada telefónica)", "喂，你是王先生吗?"],
  ["42", "Noun", "家", "jiā", "Home", "La Casa", "你家在哪儿？"],
  ["43", "Noun", "学校", "xuéxiào", "School", "El colegio", "我在学校工作。"],
  ["44", "Noun", "饭店", "fàndiàn", "Restaurant", "El restaurante", "这个饭店怎么样"],
  ["45", "Noun", "商店", "shāngdiàn", "Store", "La tienda", "妈妈去商店买东西了。"],
  ["46", "Noun", "医院", "yīyuàn", "Hospital", "El hospital", "他在医院住了一个月。"],
  ["47", "Noun", "火车站", "huǒchēzhàn", "Train station", "La estación de tren", "火车站在哪里?"],
  ["48", "Noun", "中国", "zhōngguó", "China", "China", "我想去中国学汉语。"],
  ["49", "Noun", "北京", "běijīng", "Beijing", "Pekín", "下星期我会去北京。"],
  ["50", "Noun", "上", "shàng", "Up", "Arriba", "桌子上有一本书。"],
  ["51", "Noun", "下", "xià", "Down", "Abajo", "椅子下有一快钱。"],
  ["52", "Noun", "前面", "qiánmiàn", "Front", "Delante", "小明坐在我前面。"],
  ["53", "Noun", "后面", "hòumiàn", "Behind", "Detrás", "后面那个人是谁"],
  ["54", "Noun", "里", "lǐ", "Inside", "Dentro", "茶在杯子里。"],
  ["55", "Noun", "今天", "jīntiān", "Today", "Hoy", "今天天气很好。"],
  ["56", "Noun", "明天", "míngtiān", "Tomorrow", "Mañana", "明天星期几？"],
  ["57", "Noun", "昨天", "zuótiān", "Yesterday", "Ayer", "昨天我没去学校。"],
  ["58", "Noun", "下午", "shàngwǔ", "Morning", "La mañana", "今天上午我看见了王老师。"],
  ["59", "Noun", "中午", "zhōngwǔ", "Noon", "El mediodía", "你中午回家吃饭吗"],
  ["60", "Noun", "下午", "xiàwǔ", "Afternoon", "La tarde", "我下午三点去看电影。"],
  ["61", "Noun", "年", "nián", "Year", "El año", "我们认识十年了。"],
  ["62", "Noun", "月", "yuè", "Month", "El mes", "今天是八月三号，星期五。"],
  ["63", "Noun", "日", "rì", "Day", "El día", "八月八日是我的生日。"],
  ["64", "Noun", "星期", "xīngqī", "Week", "La semana", "他会家住一个星期。"],
  ["65", "Noun", "点", "diǎn", "Dot, spot", "Punto, hora", "现在是下午三点。"],
  ["66", "Noun", "分钟", "fēnzhōng", "Minute", "Minuto", "我二十分钟后回家。"],
  ["67", "Noun", "现在", "xiànzài", "Now", "Ahora", "你现在在做什么。"],
  ["68", "Noun", "时候", "shíhou", "Time, moment", "Tiempo, momento", "这个时候他们都不在家。"],
  ["69", "Noun", "爸爸", "bàba", "Father, dad", "Padre, papá", "我爸爸是医生。"],
  ["70", "Noun", "妈妈", "māma", "Mother, mum", "Madre, mamá", "我很爱我的妈妈。"],
  ["71", "Noun", "儿子", "érzi", "Son", "Hijo", "他是我儿子。"],
  ["72", "Noun", "女儿", "nǚér", "Daughter", "Hija", "她的女儿很漂亮。"],
  ["73", "Noun", "老师", "lǎoshī", "Teacher", "El profesor", "我有三个汉语老师。"],
  ["74", "Noun", "学生", "xuéshēng", "Student", "El estudiante", "我是王老师的学生。"],
  ["75", "Noun", "同学", "tóngxué", "Classmate", "Compañero de clase", "他们都是我的同学。"],
  ["76", "Noun", "朋友", "péngyou", "Friend", "Amigo", "我们是好朋友。"],
  ["77", "Noun", "医生", "yīshēng", "Doctor", "Doctor", "我妈妈也是医生。"],
  ["78", "Noun", "先生", "xiānsheng", "Mr. , Sir", "Mister, señor", "王先生，你好！"],
  ["79", "Noun", "小姐", "xiǎojiě", "Miss, young lady", "Miss, señora", "张小姐喜欢看电影。"],
  ["80", "Noun", "衣服", "yīfu", "Clothes", "La ropa", "我买了很多衣服。"],
  ["81", "Noun", "水", "shuǐ", "Water", "El agua", "我想喝水。"],
  ["82", "Noun", "菜", "cài", "Vegetable, dish, cuisine", "La verdura, El plato, La cocina", "我在家里学习做菜。"],
  ["83", "Noun", "米饭", "mǐfàn", "Cooked rice", "El arroz", "我不喜欢吃米饭。"],
  ["84", "Noun", "水果", "shuǐguǒ", "Fruit", "la fruta", "妈妈去商店买水果了。"],
  ["85", "Noun", "苹果", "píngguǒ", "Apple", "La manzana", "桌子上有一个苹果。"],
  ["86", "Noun", "茶", "chá", "Tea", "El té", "你喜欢喝茶吗。"],
  ["87", "Noun", "杯子", "bēizi", "Cup, glass", "El vaso, La copa", "我想买一个杯子。"],
  ["88", "Noun", "钱", "qián", "Money", "El dinero", "那个杯子多少钱?"],
  ["89", "Noun", "飞机", "fēijī", "Airplane", "El avión", "我们坐飞机去北京。"],
  ["90", "Noun", "出租车", "chūzūchē", "Taxi, cab", "El taxi", "我坐出租车去学校。"],
  ["91", "Noun", "电视", "diànshì", "Television", "La televisión", "我不想看电视。"],
  ["92", "Noun", "电脑", "diànnǎo", "Computer", "El ordenador", "这是谁的电脑?"],
  ["93", "Noun", "电影", "diànyǐng", "Movie", "La película", "这个电影很好看。"],
  ["94", "Noun", "天气", "tiānqì", "Weather", "El tiempo", "明天天气很好。"],
  ["95", "Noun", "狗", "gǒu", "Dog", "Perro", "小狗在睡觉。"],
  ["96", "Noun", "猫", "māo", "Cat", "Gato", "我的小猫在哪儿?"],
  ["97", "Noun", "东西", "dōngxi", "Thing, stuff", "La cosa", "我想去商店买东西。"],
  ["98", "Noun", "人", "rén", "Human, person", "La persona", "那儿有很多人。"],
  ["99", "Noun", "名字", "míngzi", "Name", "El nombre", "你的名字怎么写?"],
  ["100", "Noun", "书", "shū", "Book", "El libro", "这些书是你的吗?"],
  ["101", "Noun", "汉语", "hànyǔ", "Chinese(language)", "El idioma chino", "我会说汉语。"],
  ["102", "Noun", "字", "zì", "Character", "El carácter", "这个字我不认识。"],
  ["103", "Noun", "桌子", "zhuōzi", "Table, desk", "La mesa", "桌子上有一杯茶。"],
  ["104", "Noun", "椅子", "yǐzi", "Chair", "La silla", "椅子上有一本书。"],
  ["105", "Verb", "谢谢", "xièxie", "To thank(thanks)", "Agradecer(gracias)", "谢谢你请我看电影。"],
  ["106", "Verb", "不客气", "búkèqì", "You're welcome", "De nada", "不客气!"],
  ["107", "Verb", "再见", "zàijiàn", "goodbye, to see you around", "Adios, verte alrededor", "我回家了，再见。"],
  ["108", "Verb", "请", "qǐng", "(polite) please, invite", "(educado) por favor, invitar", "你请坐。"],
  ["109", "Verb", "对不起", "duìbùqǐ", "To be sorry", "Lo siento", "对不起，我不能去看你了。"],
  ["110", "Verb", "没关系", "méiguānxì", "That's ok, it doesn't matter", "No hay de que, importar", "你喜不喜欢没关系。"],
  ["111", "Verb", "是", "shì", "To be", "Ser, estar", "他是医生。"],
  ["112", "Verb", "有", "yǒu", "To have, there be", "Tener, hay", "我有一本汉语书。"],
  ["113", "Verb", "看", "kàn", "To look at, to watch, to read", "Mirar, ver, leer", "妈妈在家看电影。"],
  ["114", "Verb", "听", "tīng", "To listen", "Escuchar", "我想听你说汉语。"],
  ["115", "Verb", "说", "shuō", "To speak, to say", "Hablar, decir", "他说他喜欢喝茶。"],
  ["116", "Verb", "读", "dú", "To read", "Leer", "这个字怎么读?"],
  ["117", "Verb", "写", "xiě", "To write", "Escribir", "你在写什么?"],
  ["118", "Verb", "看见", "kànjiàn", "(be able) to see", "(ser capaz) de ver", "你看见我的杯子了吗。"],
  ["119", "Verb", "叫", "jiào", "To call, to be called", "Llamar, ser llamado", "妈妈叫我回来。"],
  ["120", "Verb", "来", "lái", "To come", "Venir", "他来中国做什么?"],
  ["121", "Verb", "回", "huí", "Go back, to return", "Volver, regresar", "我们十二点回家吃饭。"],
  ["122", "Verb", "去", "qù", "To go", "Ir", "我想去商店买东西。"],
  ["123", "Verb", "吃", "chī", "To eat", "Comer", "你喜欢吃什么?"],
  ["124", "Verb", "喝", "hē", "To drink", "Comer", "爸爸和妈妈在喝茶。"],
  ["125", "Verb", "睡觉", "shuìjiào", "To sleep", "Dormir", "我在家睡觉。"],
  ["126", "Verb", "打电话", "dǎdiànhuà", "To make a phone call", "Llamar por telefono", "李老师在打电话。"],
  ["127", "Verb", "做", "zuò", "To make, to produce", "Hacer, producir", "妈妈做的菜很好吃。"],
  ["128", "Verb", "买", "mǎi", "To buy, to purchase", "Comprar, adquirir", "我买了一本汉语书。"],
  ["129", "Verb", "开", "kāi", "To open, to drive", "Abrir, conducir", "我会开车。"],
  ["130", "Verb", "坐", "zuò", "To sit, to be seated", "Sentarse, estar sentado", "这儿不能坐。"],
  ["131", "Verb", "住", "zhù", "To live, to stay", "Vivir, permanecer", "你住在哪儿?"],
  ["132", "Verb", "学习", "xuéxí", "To study, to learn", "Estudiar, aprender", "他在学校学(习)汉语。"],
  ["133", "Verb", "工作", "gōngzuò", "Work", "Trabajar", "我每天有工作。"],
  ["134", "Verb", "下雨", "xiàyǔ", "To rain", "Llover", "今天没下雨。"],
  ["135", "Verb", "爱", "ài", "To like, to love", "Gustar, amar", "我爱你。"],
  ["136", "Verb", "喜欢", "xǐhuān", "To like, to be fond of", "Gustar, ser aficionado a ", "爸爸喜欢吃水果。"],
  ["137", "Verb", "想", "xiǎng", "To want, would like", "Querer, Desear ", "我想看电视。"],
  ["138", "Verb", "认识", "rènshi", "To know, understand", "Conocer, entender", "我认识那个人。"],
  ["139", "Verb", "会", "huì", "Can , to be able to", "Poder, ser capaz de", "他不会做中国菜。"],
  ["140", "Verb", "能", "néng", "Can, may", "Poder, ser posible", "明天你能来我家吗。"],
  ["141", "Adjetive", "好", "hǎo", "Good, fine", "Bueno", "今天天气很好。"],
  ["142", "Adjetive", "大", "dà", "Big、old", "Grande, viejo", "你今年多大?"],
  ["143", "Adjetive", "小", "xiǎo", "Small, little", "Pequeño", "小狗在哪儿?"],
  ["144", "Adjetive", "多", "duō", "Many, much", "Mucho", "这个学校有很多学生。"],
  ["145", "Adjetive", "少", "shǎo", "Litlle, few", "Poco", "他买了不少衣服。"],
  ["146", "Adjetive", "冷", "lěng", "Cold", "Frio", "昨年很冷。"],
  ["147", "Adjetive", "热", "rè", "Hot", "Calor", "明天不冷也不热。"],
  ["148", "Adjetive", "高兴", "gāoxìng", "Glad, happy", "Feliz, contento", "妈妈今天很高兴。"],
  ["149", "Adjetive", "漂亮", "piàoliàng", "Beautiful, pretty", "Bonito, precioso", "我有一个漂亮的杯子。"],
  ["150", "Adverb", "不", "bù", "No, not", "No", "我不是老师。"],
  ["151", "Adverb", "没", "méi", "No, there is not", "No, no hay", "我没(有)去学校。"],
  ["152", "Adverb", "很", "hěn", "Very, quite", "Muy, mucho", "我很喜欢吃苹果。"],
  ["153", "Adverb", "太", "tài", "Too, excessively", "Demasiado", "今天太热了。"],
  ["154", "Adverb", "都", "dōu", "Both, all", "Ambos, todo", "他们都是学生。"],
]
