export const hsk2 = [
  ["1", "Personal Pronoun", "您", "nín", "You(Polite)", "Usted", ""],
  ["2", "Personal Pronoun", "它", "tā", "it", "eso(cosa)", ""],
  ["3", "Personal Pronoun", "大家", "dàjiā", "all; everybody", "todos", ""],
  ["4", "Personal Pronoun", "每", "měi", "every; each; per", "todo; cada", ""],
  ["5", "Interrogative Pronoun", "为什么", "wèishénme", "why", "por que", ""],
  ["6", "Numeral", "两", "liǎng", "two; both", "dos; ambos", ""],
  ["7", "Numeral", "百", "bǎi", "hundred", "cien", ""],
  ["8", "Numeral", "千", "qiān", "thousand", "mil", ""],
  ["9", "Numeral", "第一", "dìyī", "first", "el primero", ""],
  ["10", "Quantifier", "次", "cì", "time", "la vez", ""],
  ["11", "Quantifier", "公斤", "gōngjīn", "kilogram(kg)", "kilogramo(kg)", ""],
  [
    "12",
    "Quantifier",
    "元",
    "yuán",
    "yuan(monetary unit of China)",
    "yuan(unidad monetaria de China)",
    ""
  ],
  [
    "13",
    "Quantifier",
    "件",
    "jiàn",
    "for clothing, furniture, luggage, etc",
    "para ropa, muebles, maletas. etc",
    ""
  ],
  [
    "14",
    "Quantifier",
    "张",
    "zhāng",
    "for bed, desk, paper, face, etc",
    "para camas, escritorio, papel, cara, etc",
    ""
  ],
  ["15", "Conjuction", "因为", "yīnwèi", "because; as", "porque; como", ""],
  [
    "16",
    "Conjuction",
    "所以",
    "suǒyǐ",
    "as a result; so",
    "como resultado; entonces",
    ""
  ],
  [
    "17",
    "Conjuction",
    "但是",
    "dànshì",
    "but; yet; still",
    "pero; todavia; aun",
    ""
  ],
  [
    "18",
    "Preposition",
    "从",
    "cóng",
    "from(a time, a place, or a point of view)",
    "desde(un tiempo, un lugar o un punto de vista)",
    ""
  ],
  [
    "19",
    "Preposition",
    "对",
    "duì",
    "with regard to; concerning",
    "con respecto a; sobre",
    ""
  ],
  ["20", "Preposition", "此", "cǐ", "this", "este", ""],
  [
    "21",
    "Preposition",
    "向",
    "xiàng",
    "to; towards; in the direction of",
    "a; hacia; en direccion a ",
    ""
  ],
  [
    "22",
    "Preposition",
    "离",
    "lí",
    "leave; part from",
    "salir; partir desde",
    ""
  ],
  [
    "23",
    "Auxiliary",
    "得",
    "de",
    "after verb/adj to express possibility/capability",
    "despues de un verbo/adj para expresar posibilidad/capacidad",
    ""
  ],
  [
    "24",
    "Auxiliary",
    "着",
    "zhe",
    "added to verb/adj to indicate continued action",
    "junto a un verbo/adj para indicar accion continuada",
    ""
  ],
  [
    "25",
    "Auxiliary",
    "过",
    "guo",
    "after verb/adj to indicate compleation of and action",
    "despues de un verbo/adj para expresar pasado",
    ""
  ],
  [
    "26",
    "Auxiliary",
    "吧",
    "ba",
    "indicating a suggestion, request or mild command",
    "indica una sugerencia, solicitud o comando leve",
    ""
  ],
  ["27", "Noun", "机场", "jīchǎng", "airport", "el aeropuerto", ""],
  ["28", "Noun", "教室", "jiàoshì", "classroom", "la clase", ""],
  ["29", "Noun", "房间", "fángjiān", "room", "la habitacion", ""],
  ["30", "Noun", "路", "lù", "Road", "La carretera", "这个路不好走。"],
  ["32", "Noun", "左边", "zuǒbiān", "left", "la izquierda", "你往左边站一点儿。"],
  ["33", "Noun", "右边", "yòubiān", "right", "la derecha", "右边的电梯坏了。"],
  ["34", "Noun", "外", "wài", "outside; exterior", "fuera; exterior", "门外听了一辆新车。"],
  ["35", "Noun", "旁边", "pángbiān", "side", "el lado", "我想坐在窗户旁边。"],
  [
    "36",
    "Noun",
    "早上",
    "zǎoshàng",
    "(early) morning",
    "(temprano) la mañana",
    "你今天早上吃了什么？"
  ],
  ["37", "Noun", "晚上", "wǎnshàng", "evening; night", "la noche", "你明天晚上做什么？"],
  ["38", "Noun", "小时", "xiǎoshí", "hour", "la hora", "我们每天要工作八个小时。"],
  [
    "39",
    "Noun",
    "时间",
    "shíjiān",
    "(the concept of time) time",
    "(el concepto de tiempo) tiempo",
    "他病了好长时间。"
  ],
  ["40", "Noun", "去年", "qùnián", "last year", "el año pasado", "我去年就已经毕业了。"],
  ["41", "Noun", "号", "hào", "number", "el numero", ""],
  ["42", "Noun", "生日", "shēngrì", "birthday", "el cumpleaños", "我刚过完25岁的生日。"],
  ["43", "Noun", "哥哥", "gēge", "(elder) brother", "el hermano mayor", "我真希望我有一个哥哥。"],
  ["44", "Noun", "姐姐", "jiějie", "(elder) sister", "la hermana mayor", "我姐姐最近在减肥。"],
  ["45", "Noun", "弟弟", "dìdi", "younger brother", "el hermano menor", "我弟弟很喜欢运动。"],
  ["46", "Noun", "妹妹", "mèimei", "younger sister", "la hermana menor", "姐姐比妹妹高一点儿。"],
  ["47", "Noun", "丈夫", "zhàngfu", "husband", "el marido", "她决定和她的丈夫离婚。"],
  ["48", "Noun", "妻子", "qīzi", "wife", "la mujer; la esposa", "他正在给他的妻子做早餐。"],
  [
    "49",
    "Noun",
    "孩子",
    "háizi",
    "child; son/daughter",
    "el/la niñ@; el/la hij@",
    "孩子们都很喜欢吃糖。"
  ],
  ["50", "Noun", "男人", "nánrén", "man", "el hombre", ""],
  ["51", "Noun", "女人", "nǚrén", "women", "la mujer", ""],
  ["52", "Noun", "服务员", "fúwùyuán", "waiter/waitress", "el/la camarer@", ""],
  ["53", "Noun", "鱼", "yú", "Fish", "El pescado", "这条河里有很多鱼。"],
  [
    "54",
    "Noun",
    "羊肉",
    "yángròu",
    "Mutton",
    "Carne de cordero",
    "你吃过羊肉火锅吗。"
  ],
  ["55", "Noun", "牛奶", "niúnǎi", "Milk", "La leche", "我要去超市买牛奶。"],
  ["56", "Noun", "鸡蛋", "jīdàn", "Egg", "El huevo", "十块钱能买几个鸡蛋?"],
  ["57", "Noun", "西瓜", "xīguā", "Watermelon", "La sandía", "这个西瓜不甜。"],
  ["58", "Noun", "咖啡", "kāfēi", "Coffee", "El café", "我想和一杯咖啡。"],
  ["59", "Noun", "自行车", "zìxíngchē", "bicycle; bike", "la bicicleta", ""],
  ["60", "Noun", "船", "chuán", "boat; ship", "el barco; la embarcacion", ""],
  ["61", "Noun", "雪", "xué", "Snow", "La nieve", "今年冬天会下雪吗。"],
  ["62", "Noun", "药", "yào", "Medicine", "La medicina", "生病了就应该吃药。"],
  [
    "63",
    "Noun",
    "手机",
    "shǒujī",
    "Cell phone",
    "El teléfono móvil",
    "他用手机给我拍了一些照片。"
  ],
  [
    "64",
    "Noun",
    "手表",
    "shǒubiǎo",
    "Watch",
    "El reloj",
    "妈妈给我买了一个新手表。"
  ],
  ["65", "Noun", "眼睛", "yǎnjīng", "Eye", "El ojo", "他有一双漂亮的蓝眼睛。"],
  ["66", "Noun", "身体", "shēntǐ", "Body", "El cuerpo", "你最近身体怎么样?"],
  [
    "67",
    "Noun",
    "公共汽车",
    "gōnggòngqìchē",
    "Bus",
    "El autobús",
    "我爸爸是公共汽车司机。"
  ],
  [
    "68",
    "Noun",
    "报纸",
    "bàozhǐ",
    "Newspaper",
    "El periódico",
    "爷爷常常让我给他读报纸。"
  ],
  ["69", "Noun", "门", "mén", "Door", "La puerta", "请帮我开一下门。"],
  [
    "70",
    "Noun",
    "题",
    "tí",
    "Question, problem",
    "La pregunta, el problema",
    "这倒数学题怎么做？"
  ],
  [
    "71",
    "Noun",
    "课",
    "kè",
    "Class, lesson",
    "La clase, la lección",
    "我很喜欢上汉语课。"
  ],
  ["72", "Noun", "姓", "xìng", "surname; family name", "apellido", ""],
  [
    "73",
    "Noun",
    "问题",
    "wèntí",
    "question; problem; issue",
    "la pregunta; el problema",
    "请你回答我的问题。"
  ],
  [
    "74",
    "Noun",
    "事情",
    "shìqing",
    "affair; matter; thing",
    "asunto; cosa*(que hacer)",
    ""
  ],
  [
    "75",
    "Noun",
    "考试",
    "kǎoshì",
    "Test, exam",
    "El test, el examen",
    "这次考试很简单。"
  ],
  ["76", "Noun", "票", "piào", "Ticket", "El billete", "这个公园不需要们票。"],
  [
    "77",
    "Noun",
    "意思",
    "yìsi",
    "meaning; idea",
    "el significado; la idea",
    ""
  ],
  ["78", "Noun", "颜色", "yánsè", "color", "el color", "他的眼睛是什么颜色的？"],
  [
    "79",
    "Verb",
    "欢迎",
    "huānyíng",
    "To welcome; greet",
    "Dar la bienvenida",
    ""
  ],
  ["80", "Verb", "问", "wèn", "To ask", "Preguntar", ""],
  ["81", "Verb", "走", "zǒu", "To walk", "Andar", ""],
  ["82", "Verb", "进", "jìn", "To enter", "Entrar", ""],
  ["83", "Verb", "跑步", "pǎobù", "To run", "Correr", ""],
  ["84", "Verb", "到", "dào", "To arrive", "Llegar", ""],
  ["85", "Verb", "穿", "chuān", "To wear", "", ""],
  ["86", "Verb", "出", "chū", "To exit", "Salir", ""],
  ["87", "Verb", "洗", "xǐ", "To wash", "Lavar", ""],
  ["88", "Verb", "给", "gěi", "To give", "Dar", ""],
  ["91", "Verb", "找", "zhǎo", "To find", "Encontrar", ""],
  ["92", "Verb", "懂", "dǒng", "To understand", "Entender", ""],
  ["93", "Verb", "笑", "xiào", "To laugh", "Reir ", ""],
  ["94", "Verb", "回答", "huídá", "To answer", "Contestar", ""],
  ["95", "Verb", "告诉", "gàosù", "To tell", "Decir", ""],
  ["96", "Verb", "准备", "zhǔnbèi", "To prepare", "Preparar", ""],
  ["97", "Verb", "开始", "kāishǐ", "To start", "Empezar", ""],
  ["98", "Verb", "介绍", "jièshào", "To introduce", "Presentar", ""],
  ["99", "Verb", "帮助", "bāngzhù", "To help", "Ayudar", ""],
  ["100", "Verb", "玩", "wán", "To play", "Jugar", ""],
  ["101", "Verb", "送", "sòng", "To send", "Enviar", ""],
  ["102", "Verb", "等", "děng", "To wait", "Esperar", ""],
  ["103", "Verb", "让", "ràng", "To let", "Permitir", ""],
  ["104", "Verb", "起床", "qǐchuáng", "To get up", "Levantarse", ""],
  ["105", "Verb", "唱歌", "chànggē", "To sing", "Cantar", ""],
  ["106", "Verb", "跳舞", "tiàowǔ", "To dance", "Bailar", ""],
  ["107", "Verb", "旅游", "lǚyóu", "To travel", "Viajar", ""],
  ["108", "Verb", "上班", "shàngbān", "To start work", "Empezar a trabajar", ""],
  ["109", "Verb", "生病", "shēngbìng", "To fall ill", "Enfermar", ""],
  ["110", "Verb", "休息", "xiūxi", "To rest", "Descansar", ""],
  ["111", "Verb", "运动", "yùndòng", "To exercise", "Hacer ejercicio", "医生告诉我要多做运动。"],
  ["112", "Verb", "游泳", "yóuyǒng", "To swim", "Nadar", ""],
  ["113", "Verb", "踢足球", "tīzúqiú", "To play football", "Jugar al futbol", ""],
  ["114", "Verb", "打篮球", "dǎlánqiú", "To play basketball", "Jugar al baloncesto", ""],
  ["115", "Verb", "完", "wán", "To finish", "Finalizar", ""],
  ["116", "Verb", "觉得", "juédé", "To think", "Pensar", ""],
  ["117", "Verb", "知道", "zhīdào", "To know", "Saber", ""],
  ["118", "Verb", "希望", "xīwàng", "To wish", "Desear", ""],
  ["119", "Verb", "可以", "kěyǐ", "Can (allow)", "Poder (Permitir)", ""],
  ["120", "Verb", "要", "yào", "To want", "Querer", ""],
  ["121", "Verb", "可能", "kěnéng", "Might (happen)", "Poder (Suceder)", ""],
  ["122", "Adjetive", "高", "gāo", "Tall", "Alto", ""],
  ["123", "Adjetive", "红", "hóng", "Red", "Rojo", ""],
  ["124", "Adjetive", "白", "bái", "White", "Blanco", ""],
  ["125", "Adjetive", "黑", "hēi", "Black", "Negro", ""],
  ["126", "Adjetive", "忙", "máng", "Busy", "Ocupado", ""],
  ["127", "Adjetive", "快", "kuài", "Fast", "Rapido", ""],
  ["128", "Adjetive", "慢", "màn", "Slow", "Despacio", ""],
  ["129", "Adjetive", "远", "yuǎn", "Far", "Lejos", ""],
  ["130", "Adjetive", "近", "jìn", "Near", "Cerca", ""],
  ["131", "Adjetive", "好吃", "hǎochī", "Delicious", "Rico", ""],
  ["132", "Adjetive", "累", "lèi", "(be) Tired", "(estar) cansado", ""],
  ["133", "Adjetive", "长", "cháng", "Long", "Largo", ""],
  ["134", "Adjetive", "新", "xīn", "New", "Nuevo", ""],
  ["135", "Adjetive", "贵", "guì", "Expensive", "Caro", ""],
  ["136", "Adjetive", "便宜", "piányi", "Cheap", "Barato", ""],
  ["137", "Adjetive", "晴", "qíng", "Fine; clear (weather)", "Bueno; claro (tiempo)", ""],
  ["138", "Adjetive", "阴", "yīn", "Overcast", "Nublado", ""],
  ["139", "Adjetive", "错", "cuò", "Wrong; erroneous", "Incorrecto; erroneo", ""],
  ["140", "Adjetive", "快乐", "kuàilè", "Happy", "Feliz", ""],
  ["141", "Adverb", "别", "bié", "Other", "Otro", ""],
  ["142", "Adverb", "非常", "fēicháng", "Very; extremely", "Muy; extremadamente", ""],
  ["143", "Adverb", "也", "yě", "Also; too; as well", "Tambien; ademas", ""],
  ["144", "Adverb", "还", "hái", "Still; yet", "Todavia; aun", ""],
  ["145", "Adverb", "最", "zuì", "Most; -est", "El que mas", ""],
  ["146", "Adverb", "真", "zhēn", "Really", "Enserio", ""],
  ["147", "Adverb", "正在", "zhèngzài", "In process of", "En proceso de", ""],
  ["148", "Adverb", "已经", "yǐjīng", "Already", "Ya", ""],
  ["149", "Adverb", "一起", "yìqǐ", "Together", "Juntos", ""],
  ["150", "Adverb", "再", "zài", "Again; once more", "De nuevo; una vez mas", ""],
  ["151", "Adverb", "就", "jiǜ", "At once; right away", "En seguida; inmediatamente", ""]
];
